apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: analytics-kafka-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.6.1
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: ingress
        tls: true
        configuration:
          class: haproxy
          bootstrap:
            host: 192.168.1.10
          brokers:
            - broker: 0
              host: 192.168.1.11
            - broker: 1
              host: 192.168.1.12
            - broker: 2
              host: 192.168.1.13
    config:
      offsets.topic.replication.factor: 3
      default.replication.factor: 3
      min.insync.replicas: 2
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      inter.broker.protocol.version: "3.6"
      auto.create.topics.enable: true
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 20Gi
          deleteClaim: true
          class: standard
    resources:
      limits:
        cpu: 1000m
        memory: 1824Mi
      requests:
        cpu: 600m
        memory: 1450Mi
  zookeeper:
    replicas: 1
    storage:
      class: standard
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
    resources:
      limits:
        memory: 1024Mi
      requests:
        cpu: 150m
        memory: 512Mi
  entityOperator:
    topicOperator:
      resources:
        limits:
          memory: 512Mi
          cpu: 300m
        requests:
          memory: 400Mi
          cpu: 30m
    userOperator:
      resources:
        limits:
          memory: 512Mi
          cpu: 300m
        requests:
          memory: 300Mi
          cpu: 20m
